# Generated by Django 3.2.7 on 2021-12-16 11:47

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=400)),
                ('main_technology_used', models.CharField(max_length=30, null=True)),
                ('screenshot', cloudinary.models.CloudinaryField(max_length=255, verbose_name='screenshot')),
                ('live_link', models.URLField(max_length=100)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('project_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_rate', models.PositiveSmallIntegerField(choices=[(1, '1 - Unlikeable'), (2, '2 - Horrible'), (3, '3 - Hmmmm'), (4, '4 - Bad'), (5, '5 - Fine'), (6, '6 - Good'), (7, '7 - Very Good'), (8, '8 - Likeable'), (9, '9 - Perfect'), (10, '10 - Awesome')])),
                ('usability_rate', models.PositiveSmallIntegerField(choices=[(1, '1 - Unlikeable'), (2, '2 - Horrible'), (3, '3 - Hmmmm'), (4, '4 - Bad'), (5, '5 - Fine'), (6, '6 - Good'), (7, '7 - Very Good'), (8, '8 - Likeable'), (9, '9 - Perfect'), (10, '10 - Awesome')])),
                ('content_rate', models.PositiveSmallIntegerField(choices=[(1, '1 - Unlikeable'), (2, '2 - Horrible'), (3, '3 - Hmmmm'), (4, '4 - Bad'), (5, '5 - Fine'), (6, '6 - Good'), (7, '7 - Very Good'), (8, '8 - Likeable'), (9, '9 - Perfect'), (10, '10 - Awesome')])),
                ('review', models.TextField(blank=True, max_length=1000)),
                ('date', models.DateField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wins.projects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=400)),
                ('country', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=10)),
                ('picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
